version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - NODE_VERSION=18
    image: uniadaptivelti-front
    container_name: uniadaptivelti-front
    restart: unless-stopped
    networks:
      - uniadaptive-network
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
networks:
  uniadaptive-network:
    driver: bridge

