version: "3.9"

services:
  app:
    build:
      context: .
      image: uniadaptivelti-front
      container_name: uniadaptivelti-front
      restart: unless-stopped
      networks:
        - uniadaptive-network
      args:
        - NODE_VERSION=18
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
networks:
  uniadaptive-network:
    driver: bridge
