version: "3.9"

services:
  app:
    build:
      context: .
      image: UNIAdaptiveLTI-Front
      container_name: UNIAdaptiveLTI-Front
      restart: unless-stopped
      networks:
        - uniadaptive-network
      args:
        - NODE_VERSION=18
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_MODE=production
networks:
  uniadaptive-network:
    driver: bridge