version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - NODE_VERSION=18
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NEXT_MODE=dev
